query approvaluploadID($id:UUID!){
  upload(id:$id){
    id
    fileIacard
    fileEvent
    iacardName
    eventName
    status
    userId
      user{
        id
        firstname
        lastname
        email
        password
        gender
        phone
        idcard
        birthdate
        profileimageurl
      }
    eventId
      event{
        id
        eventnameTh
      }
  }
  
}

