query approvaluploadID($id:UUID!){
  requestapproval(id:$id){
    id
    linkdrive
    status
    userId
      user{
        id
        firstname
        lastname
        email
        password
        gender
        phone
        idcard
        birthdate
        profileimageurl
      }
    eventId
      event{
        id
        eventnameTh
      }
  }
  
}

