query eventID($id: UUID!) {
  event(id: $id) {
    id
    eventnameTh
    eventnameEn
    locationTh
    locationEn
    linkurl
    coverphotourl
    startdate
    enddate
    openforapplications
    applicationdeadline
    descriptionTh
    descriptionEn
    hashtag
    organizer
    latitude
    longitude
    poster
    awardphoto
    shirtsize
    facebookurl
    status
    
    provinceId
    province {
      id
      provinceTh
      provinceEn
    }
    eventgroupId
    eventgroup {
      id
      eventgroupnameTh
      eventgroupnameEn
    }
   requestapprovals{
      nodes{
        id
        status
      }
    }
  }
  eventgroups(orderBy: EVENTGROUPNAME_TH_ASC) {
    nodes {
      id
      eventgroupnameTh
      eventgroupnameEn
      follow
    }
  }
  provinces(orderBy: PROVINCE_TH_ASC) {
    nodes {
      id
      provinceTh
      provinceEn
    }
  } 
}