query environmenteventID($id:UUID!){
  environmentevent(id:$id){
    id
    eventId
    event{
      id
      eventnameTh
    }environmentId
    environment{
      id
      environmentTh
    }
  }environments{
    nodes{
      id
      environmentTh
    }
  }events{
    nodes{
      id
      eventnameTh
    }
  }environmentevents{
    totalCount
    nodes{
      id
      eventId
      event{
        eventnameTh
      }environmentId
      environment{
        environmentTh
      }
    }
  }
}