query event($id:UUID!){
  event(id:$id){
    id
    eventnameTh
      eventnameEn
      locationTh
      locationEn
      linkurl
      coverphotourl
      startdate
      enddate
      openforapplications
      applicationdeadline
      descriptionTh
      descriptionEn
      hashtag
      organizer
      latitude
      longitude
      poster
      awardphoto
      shirtsize
      facebookurl
      avgrankscore
      provinceId
    province{
      provinceTh
      provinceEn
    }eventgroup{
      id
      eventgroupnameTh
      eventgroupnameEn
      followings{
        nodes{
          id
          userId
          eventgroupId
        }
      }
    }
    racetypeevents{
      nodes{
        race{
          raceTh
          raceEn
          price
          distance
        }
      }
    }reviews{
      totalCount
      nodes{
        review
        userId
        eventId
        user{
          id
          firstname
          lastname
          profileimageurl
        }
      }
    }
  }
  rankings{
    totalCount
    nodes{
      rankscore
      user{
        id
        firstname
        lastname
      }
      event{
        id
        eventnameTh
        eventnameEn
      }
      typerank{
        id
        ranknameTh
        ranknameEn
      }
    }
  } 
  users{
    nodes{
      id
      firstname
      lastname
      profileimageurl
    }
  }
  follownames{
    nodes{
      id
      followName
      status
    }
  }
}