query eventtypeof($id:UUID!){
  event(id:$id){
    id
    eventnameTh
      eventnameEn
      locationTh
      locationEn
      linkurl
      coverphotourl
      startdate
      enddate
      openforapplications
      applicationdeadline
      descriptionTh
      descriptionEn
      hashtag
      organizer
      latitude
      longitude
      poster
      awardphoto
      shirtsize
      facebookurl
      provinceId
    province{
      provinceTh
      provinceEn
    }eventgroup{
      eventgroupnameTh
      eventgroupnameEn
    }
    racetypeevents{
      nodes{
        race{
          raceTh
          raceEn
          price
          distance
        }
      }
    }
    rankings{
      totalCount
      nodes{
        rankscore
        event{
          eventnameTh
          eventnameEn
        }
        user{
          firstname
          lastname
        }
        typerank{
          ranknameTh
          ranknameEn
        }
      }
    }
  }
  typeofranks{
    nodes{
        id
      ranknameTh
      discriptionTh
      ranknameEn
      discriptionEn
    }
  }
  events{
    nodes{
      eventnameTh
      eventnameEn
    }
  }
}
  