query users {
  users {
    nodes{
      id
    firstname
      lastname
      email
      password
      phone
      idcard
      birthdate
      gender
      profileimageurl
       requestapprovals(
    orderBy: EVENT_ID_ASC
    filter: {status:{equalTo:true}}
    ){
      totalCount
        nodes{
          id
      		linkdrive
      		status
      		userId
          eventId
          event{
        		id
        		eventnameTh
            coverphotourl
            organizer
            startdate
            enddate
            linkurl
      }
        }
      }
    }
  }
}