query searchevent($eventnameTh:String!){
  events(orderBy:APPLICATIONDEADLINE_ASC,filter:{eventnameTh:{includes:$eventnameTh}}){
    nodes{
      id
     eventnameTh
      eventnameEn
      locationTh
      locationEn
      linkurl
      coverphotourl
      startdate
      enddate
      openforapplications
      applicationdeadline
      descriptionTh
      descriptionEn
      hashtag
      organizer
      latitude
      longitude
      poster
      awardphoto
      shirtsize
      facebookurl
      provinceId
      province{
        provinceTh
        provinceEn
      }
      yearId
      adminId
    }
  }provinces(orderBy:PROVINCE_TH_ASC){
    nodes{
      id
      provinceTh
      provinceEn
    }
  }categories{
    nodes{
      id
      categorynameTh
      categorynameEn
    }
  }environments{
    nodes{
      id
      environmentTh
      environmentEn
    }
  }
  }
 