query searcheventgroup($eventgroupnameTh: String!) {
  eventgroups(
    orderBy: EVENTGROUPNAME_TH_ASC
    filter: { eventgroupnameTh: { includes: $eventgroupnameTh } }
  ) {
    totalCount
    nodes {
      id
      eventgroupnameTh
      eventgroupnameEn
      eventgroupimageurl
      events {
        nodes {
          id
          eventnameTh
          eventnameEn
          locationTh
          locationEn
          linkurl
          coverphotourl
          startdate
          enddate
          openforapplications
          applicationdeadline
          descriptionTh
          descriptionEn
          hashtag
          organizer
          latitude
          longitude
          poster
          awardphoto
          shirtsize
          facebookurl
          provinceId
          province {
            provinceTh
            provinceEn
          }
          eventgroupId
        }
      }
    }
  }
}
