query searchcategory($categoryId: UUID) {
  categories(orderBy: CATEGORYNAME_TH_ASC) {
    nodes {
      id
      categorynameTh
      categorynameEn
    }
  }
  categoryevents(filter: { categoryId: { equalTo: $categoryId } }) {
    nodes {
      id
      event {
        id
        eventnameTh
        eventnameEn
        locationTh
        locationEn
        coverphotourl
        startdate
        enddate
        openforapplications
        applicationdeadline
        hashtag
        provinceId
        province {
          provinceTh
          provinceEn
        }
      }
    }
  }
}
