FROM graphile/postgraphile:v4.12.3

RUN yarn add @graphile-contrib/pg-simplify-inflector postgraphile-plugin-connection-filter

# RUN yarn add @graphile-contrib/pg-simplify-inflector postgraphile-plugin-connection-filter